---
meta:
  environment: rabbitmq-smoke-tests-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu-trusty-go_agent
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: smoke-tests
    instances: 2
    networks:
      - name: smoke-tests
        static_ips: ~
    properties:
      cf:
        api_url: https://api.bosh-lite.com
        apps_domain: bosh-lite.com
      rabbitmq:
        skip_ssl: true

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: smoke-tests
  # Assumes up to 5 VMs, including 1 static and 4 dynamic.
  # Plus 5 (double the size) unused IPs, due to BOSH bug/quirk.
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.13.0/30
    reserved:
    - 10.244.13.1
    static:
    - 10.244.13.2

  - cloud_properties:
      name: random
    range: 10.244.13.4/30
    reserved:
    - 10.244.13.5
    static: []
  - cloud_properties:
      name: random
    range: 10.244.13.8/30
    reserved:
    - 10.244.13.9
    static: []
  - cloud_properties:
      name: random
    range: 10.244.13.12/30
    reserved:
    - 10.244.13.13
    static: []
  - cloud_properties:
      name: random
    range: 10.244.13.16/30
    reserved:
    - 10.244.13.17
    static: []

  # Bonus double-sized network required due to BOSH oddity
  - cloud_properties:
      name: random
    range: 10.244.13.20/30
    reserved:
    - 10.244.13.21
    static: []
  - cloud_properties:
      name: random
    range: 10.244.13.24/30
    reserved:
    - 10.244.13.25
    static: []
  - cloud_properties:
      name: random
    range: 10.244.13.28/30
    reserved:
    - 10.244.13.29
    static: []
  - cloud_properties:
      name: random
    range: 10.244.13.32/30
    reserved:
    - 10.244.13.33
    static: []
  - cloud_properties:
      name: random
    range: 10.244.13.36/30
    reserved:
    - 10.244.13.37
    static: []
