---
update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: smoke-tests
    lifecycle: errand
    templates:
    - name: smoke-tests
      release: rabbitmq-smoke-tests
    instances: 1
    resource_pool: small_z1
    update:
      canaries: 10
    properties:
      cf:
        api_url: (( merge ))
        apps_domain: (( merge ))
        admin_username: admin
        admin_password: admin
      rabbitmq:
        service_name: p-rabbitmq
        plan_names: '[ "standard" ]'
        skip_ssl: (( merge ))
        password: anything_but_meow
